@extends('layouts.app')
@section('title', 'Payslip — ' . $payroll->staff->name . ' — ' . $payroll->monthLabel)
@section('page-title', 'Staff Payslip')

@section('content')

{{-- ── Action Bar (hidden on print) ───────────────────────────────────── --}}
<div class="d-flex gap-2 mb-4 d-print-none">
    <a href="{{ route('admin.staff.payroll.index', ['month' => \Carbon\Carbon::parse($payroll->payroll_month)->format('Y-m')]) }}"
       class="btn btn-outline-secondary btn-sm fw-bold">
        <i class="bi bi-arrow-left me-1"></i>Back to Payroll
    </a>
    <button onclick="window.print()" class="btn btn-success btn-sm fw-bold">
        <i class="bi bi-printer me-1"></i>Print / Save PDF
    </button>
    @if($payroll->isPaid())
        <span class="badge bg-success d-flex align-items-center px-3 ms-2">
            <i class="bi bi-lock-fill me-1"></i>PAID — {{ $payroll->payment_date?->format('d M Y') }}
        </span>
    @else
        <span class="badge bg-warning text-dark d-flex align-items-center px-3 ms-2">
            PENDING PAYMENT
        </span>
    @endif
</div>

{{-- ── Payslip Card ─────────────────────────────────────────────────────── --}}
<div class="chart-card" id="payslip-card" style="max-width: 800px; margin: 0 auto;">

    {{-- Header --}}
    <div class="text-center border-bottom pb-4 mb-4">
        <h4 class="fw-bold mb-0" style="color:#1B6B35;">PHA Foundation</h4>
        <p class="text-muted mb-2" style="font-size:13px;">Ministry of Housing &amp; Works, Government of Pakistan</p>
        <div class="d-inline-block px-4 py-2 rounded-3 fw-bold"
             style="background:#1B6B35; color:#C9A84C; font-size:15px; letter-spacing:.5px;">
            SALARY PAYSLIP — {{ strtoupper($payroll->monthLabel) }}
        </div>
    </div>

    {{-- Two-column staff info --}}
    <div class="row mb-4 g-0">
        <div class="col-md-6 pe-3">
            <table class="table table-sm table-borderless mb-0" style="font-size:13px;">
                <tr>
                    <td class="fw-bold text-muted" style="width:140px;">Staff Name</td>
                    <td class="fw-bold">{{ $payroll->staff->name }}</td>
                </tr>
                <tr>
                    <td class="fw-bold text-muted">Designation</td>
                    <td>{{ $payroll->staff->designation }}</td>
                </tr>
                @if($payroll->staff->phone)
                <tr>
                    <td class="fw-bold text-muted">Phone</td>
                    <td>{{ $payroll->staff->phone }}</td>
                </tr>
                @endif
                @if($payroll->staff->cnic)
                <tr>
                    <td class="fw-bold text-muted">CNIC</td>
                    <td>{{ $payroll->staff->cnic }}</td>
                </tr>
                @endif
                @if($payroll->staff->joining_date)
                <tr>
                    <td class="fw-bold text-muted">Joining Date</td>
                    <td>{{ $payroll->staff->joining_date->format('d M Y') }}</td>
                </tr>
                @endif
            </table>
        </div>
        <div class="col-md-6 ps-3 border-start">
            <table class="table table-sm table-borderless mb-0" style="font-size:13px;">
                <tr>
                    <td class="fw-bold text-muted" style="width:140px;">Payroll Month</td>
                    <td class="fw-bold">{{ $payroll->monthLabel }}</td>
                </tr>
                <tr>
                    <td class="fw-bold text-muted">Salary Type</td>
                    <td>
                        <span class="badge {{ $payroll->salary_type === 'monthly' ? 'bg-primary' : 'bg-info text-dark' }}">
                            {{ ucfirst($payroll->salary_type) }}
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="fw-bold text-muted">Generated By</td>
                    <td>{{ $payroll->generatedBy?->name ?? 'System' }}</td>
                </tr>
                <tr>
                    <td class="fw-bold text-muted">Payment Status</td>
                    <td>
                        @if($payroll->isPaid())
                            <span class="badge bg-success"><i class="bi bi-check-circle me-1"></i>PAID</span>
                            <span class="text-muted ms-1" style="font-size:11px;">{{ $payroll->payment_date?->format('d M Y') }}</span>
                        @else
                            <span class="badge bg-warning text-dark">PENDING</span>
                        @endif
                    </td>
                </tr>
            </table>
        </div>
    </div>

    {{-- Attendance Summary --}}
    <h6 class="fw-bold mb-3 pb-2 border-bottom" style="color:#1B6B35;">
        <i class="bi bi-calendar3 me-2"></i>Attendance Summary — {{ $payroll->monthLabel }}
    </h6>
    <div class="row g-2 mb-4">
        @foreach([
            ['Total Days',     $payroll->total_days,   '#64748b'],
            ['Present',        $payroll->present_days, '#1B6B35'],
            ['Half Day',       $payroll->half_days,    '#d97706'],
            ['Absent',         $payroll->absent_days,  '#dc2626'],
            ['Leave',          $payroll->leave_days,   '#0891b2'],
            ['Holidays',       $payroll->holiday_days, '#94a3b8'],
        ] as [$label, $value, $color])
        <div class="col-4 col-md-2">
            <div class="text-center p-2 rounded-3" style="background:#f8fafc; border:1px solid #e2e8f0;">
                <div class="fw-bold" style="font-size:24px; color:{{ $color }};">{{ $value }}</div>
                <div class="text-muted" style="font-size:10px; font-weight:600; text-transform:uppercase; letter-spacing:.5px;">{{ $label }}</div>
            </div>
        </div>
        @endforeach
    </div>

    {{-- Salary Calculation --}}
    <h6 class="fw-bold mb-3 pb-2 border-bottom" style="color:#1B6B35;">
        <i class="bi bi-calculator me-2"></i>Salary Calculation
    </h6>
    <table class="table table-bordered mb-4" style="font-size:13px;">
        <tbody>
            @if($payroll->salary_type === 'monthly')
                <tr>
                    <td class="fw-bold" style="width:60%;">Basic Salary</td>
                    <td class="text-end">Rs {{ number_format($payroll->basic_salary_snapshot, 2) }}</td>
                </tr>
                <tr>
                    <td class="fw-bold">Allowances</td>
                    <td class="text-end">Rs {{ number_format($payroll->allowances_snapshot, 2) }}</td>
                </tr>
                <tr class="table-light">
                    <td class="fw-bold">Gross Salary</td>
                    <td class="text-end fw-bold">Rs {{ number_format($payroll->gross_salary, 2) }}</td>
                </tr>
                @if($payroll->deductions > 0)
                @php
                    $workDays = $payroll->total_days - $payroll->holiday_days;
                    $perDay   = $workDays > 0 ? round($payroll->basic_salary_snapshot / $workDays, 2) : 0;
                    $effAbs   = $payroll->absent_days + ($payroll->half_days * 0.5);
                @endphp
                <tr>
                    <td class="text-danger fw-bold">
                        Deductions (Absences)<br>
                        <small class="text-muted fw-normal">
                            {{ $payroll->absent_days }} absent + {{ $payroll->half_days }}×½ = {{ $effAbs }} days
                            × Rs {{ number_format($perDay, 2) }}/day
                        </small>
                    </td>
                    <td class="text-end text-danger fw-bold">- Rs {{ number_format($payroll->deductions, 2) }}</td>
                </tr>
                @endif
            @else {{-- daily --}}
                @php $effectiveDays = $payroll->present_days + ($payroll->half_days * 0.5); @endphp
                <tr>
                    <td class="fw-bold">
                        Daily Rate × Effective Days<br>
                        <small class="text-muted fw-normal">
                            Rs {{ number_format($payroll->staff->daily_rate, 2) }}/day
                            × {{ $effectiveDays }} days
                            ({{ $payroll->present_days }}P + {{ $payroll->half_days }}½)
                        </small>
                    </td>
                    <td class="text-end">Rs {{ number_format($payroll->staff->daily_rate * $effectiveDays, 2) }}</td>
                </tr>
                <tr>
                    <td class="fw-bold">Allowances</td>
                    <td class="text-end">Rs {{ number_format($payroll->allowances_snapshot, 2) }}</td>
                </tr>
                <tr class="table-light">
                    <td class="fw-bold">Gross Salary</td>
                    <td class="text-end fw-bold">Rs {{ number_format($payroll->gross_salary, 2) }}</td>
                </tr>
            @endif
            <tr style="background:#f0fdf4;">
                <td class="fw-bold" style="font-size:16px; color:#1B6B35;">
                    <i class="bi bi-currency-rupee me-1"></i>NET SALARY PAYABLE
                </td>
                <td class="text-end fw-bold text-success" style="font-size:22px;">
                    Rs {{ number_format($payroll->net_salary, 2) }}
                </td>
            </tr>
        </tbody>
    </table>

    @if($payroll->isPaid() && $payroll->payment_remarks)
    <div class="alert alert-success" style="font-size:12px;">
        <i class="bi bi-info-circle me-1"></i>
        <strong>Payment Note:</strong> {{ $payroll->payment_remarks }}
    </div>
    @endif

    {{-- Signature block (print only) --}}
    <div class="row mt-5 pt-4 d-none d-print-flex">
        <div class="col-4 text-center">
            <div class="border-top pt-2 mt-5" style="font-size:12px;">Employee Signature</div>
        </div>
        <div class="col-4 text-center">
            <div class="border-top pt-2 mt-5" style="font-size:12px;">HR / Accounts</div>
        </div>
        <div class="col-4 text-center">
            <div class="border-top pt-2 mt-5" style="font-size:12px;">Authorized Signatory</div>
        </div>
    </div>
</div>

@push('styles')
<style>
@media print {
    body { background: white !important; color: black !important; }
    .sidebar, .topbar, .d-print-none { display: none !important; }
    .main-content { margin-left: 0 !important; padding: 20px !important; }
    .chart-card { border: 1px solid #ccc !important; box-shadow: none !important; max-width: 100% !important; }
    .d-none.d-print-flex { display: flex !important; }
    table { border-collapse: collapse !important; }
    table td, table th { border: 1px solid #999 !important; }
}
</style>
@endpush

@endsection
